---
template: "myIEEEtrantemplate.tex"
documentclass: IEEEtran
classoption: sigconf
title: A Capacitively Degenerated, Temperature-Compensated Class-AB `\\`{=latex} Parametric Residue Amplifier for SAR-Assisted Pipeline ADCs
author:
- name: Diogo André S. Dias
  affiliation:
    department: Electrical and Computers Eng.
    organization: School of Science & Technology, NOVA University of Lisbon
    city: Monte da Caparica, Almada
    country: Portugal
    orcid: https://orcid.org/0000-0002-3150-3810
bibliography: bibliography.bib
abstract: |
  This is an abstractooo...
keywords:
- residue amplifier
- capacitive degeneration technique
- analog-to-digital converter (ADC)
- successive-approximations-register (SAR) ADC
- pipeline ADC
- temperature compensation
include-before:
figPrefix:
  - "Fig."
  - "Figs."
---